### ISSUE TITLE
I cant figure out how to create a tex file

### ISSUE THREAD

**Issue by jackcrane** [waynepiekarski/XTextureExtractor#10]
Can anyone help me make a tex file for the Eurofighter Typhoon?

http://www.dmax3d.com/dmax3d/eurofighter.html

Thanks

**Comment by jackcrane** [comment]
I was just hoping to use the names screens other than what they are

**Comment by waynepiekarski** [comment]
The texture creation process is a little complicated, since you need to define a texture file with the right dimensions, and its hard to make this easy to do. For the record, here are some instructions that explain the steps to do it: https://forums.x-plane.org/index.php?/files/file/42612-xtextureextractor/&do=findComment&comment=255559

However, since the aircraft is freely available, I downloaded it and created a config file for you: https://raw.githubusercontent.com/waynepiekarski/XTextureExtractor/master/Plugin-XTextureExtractor-x64-Release/Typhoon.acf.tex

You will need to download this file and place it inside the XTextureExtractor plugin directory along with the other .tex files. This file will also be included in the next release.

Enjoy!

**Comment by waynepiekarski** [comment]
Oh one more thing, here is the texture image where you can see everything that is available. If there are other displays that you want, you need to find the coordinates in the image, and edit the .tex file. https://github.com/waynepiekarski/XTextureExtractor/blob/master/texture-typhoon.jpg
