### ISSUE TITLE
Flight Factor A320 not working

### ISSUE THREAD

**Issue by drelich** [waynepiekarski/XTextureExtractor#13]
Hi,

I just found your plugin, which made me very excited because I've been looking for a way to pop out the PFD/ND/ECAM displays onto a separate screen for a very long time.

Unfortunately, it doesn't seem to be working. The error I can see in the log.txt:
`XTextureExtractor2: Error! Mismatch texture id=9, width=256!=2048, height=256!=2048, internal format=32856!=32856
`

It works for every other aircraft I tried so it seems to be FFA320 specific problem. 

Any hint as to what I might be doing wrong? I run the latest X-Plane 11 and lates build of the FFA320 bird.

Thank you.

**Comment by waynepiekarski** [comment]
I don't own the FF A320 so I have no ability to test the latest changes on this aircraft. However, the A320 is a strange design that does the panel texture differently than every other X-Plane aircraft, it uses 3 textures instead of just the usual 1. You should use the previous v1 plugin, which sort of works, but can only export one of the textures and not all 3. It would require a total redesign of the software to support the A320 and I don't know much about it.

**Comment by drelich** [comment]
Thanks for a quick response!

When it comes to those textures, I'm not actually sure FFA320 does use any to render the main displays. At least, I couldn't find the relevant texture files in the usual places (unlike with the other planes I tested). I could find the panel textures, etc. but not the display ones. 

I do hope FF does make those displays detachable at some point. Can't figure out why they haven't done that already since they allow them to popup. I'm not an X-Plane coder but I'd hazard a guess that once you have them render in their popped-up state, it shouldn't be that difficult to render them in a new window?

**Comment by waynepiekarski** [comment]
A "traditional" X-Plane aircraft has a dedicated panel texture, where all the displays are drawn into them. So the Zibo, Laminar, SSG, and FF757/767 all seem to use this strategy. Part of the texture exists as an image in the aircraft directory, and then code draws over the top, and then it is displayed.

The FF A320 is a completely different aircraft. It seems to use C++ code for all the rendering, and is completely 100% different than anything I've seen before. So XTE basically doesn't work with it, and never will. It requires a dedicated plugin written just for this one aircraft. However, rather than looking through the aircraft files, if you go to the Developer menu and bring up the texture browser, you can find the three panel textures in there. So they do exist. Someone could write an XTE that supports it, since the textures are created in a similar way.

While FF has added popouts for the 757 and in the future will do the 767, this may not happen for the A320. FF is not a single company, and they distribute aircraft made by different developers under a common name. So the codebase is probably completely different, and they may never do the A320. The aircraft developer has the source code for their aircraft, so these things are a lot easier for them to add than someone else, but requires them to make the change. What I really like about XTE is that it works with almost every aircraft (except A320) in the X-Plane fleet with only a small config file, and no need for custom hacks for each one, since there is a standardized way that most aircraft do their panel.

**Comment by drelich** [comment]
Agreed, it would be easiest to just have FF do their thing, haha! It's a pity, from what I just found out they do have pop-out displays for their B757 FPDS update so it's not like they can't do it. Ah well...

**Comment by waynepiekarski** [comment]
The reason I wrote XTE is that no aircraft implemented pop-outs, its either very hard to do or no one cares. I'm not sure. Only the Felis Tupolev and SSG 748 implemented anything like a pop-out when I started this project.
