### ISSUE TITLE
Support for Vulkan

### ISSUE THREAD

**Issue by magazaki** [waynepiekarski/XTextureExtractor#16]
Hi, any chance this plugin could support Vulkan?

**Comment by waynepiekarski** [comment]
The latest version 1.3 of XTE supports Vulkan just fine. https://github.com/waynepiekarski/XTextureExtractor/blob/master/Uploads/XTextureExtractor-1.3.zip

However, version 2.0 with the automatic texture scanning hack does not, and I'm not sure if it will ever be possible to make that feature work since it was (ab)using undocumented SDK features.
