### ISSUE TITLE
ffa320 windows are slightly misaligned

### ISSUE THREAD

**Issue by georgegohl888** [waynepiekarski/XTextureExtractor#3]
Hey! great program and it the only saving grace for my flight sim projects. The windows on the ffa320 are slightly off on the central displays. Let me know if there are any files you need. thanks, George
![image](https://user-images.githubusercontent.com/20260159/41358856-28ea8c36-6f21-11e8-9e07-9ded0141553b.png)

**Comment by waynepiekarski** [comment]
It might be that FF has released an update for their aircraft. I don't have it myself, someone captured the texture for me. But what you can do is go into the plug-in and there will be a .tex file for the aircraft. You can edit the coordinates to tweak the top left and bottom right coordinates in pixels. If you press the Dbg button in the UI it will save out a texture_save.png file you can load into a photo editor and calculate the coordinates.

**Comment by waynepiekarski** [comment]
CDU2 looks different than your other screenshot. I suspect it is grabbing different textures each time, and getting the layout all wrong because of this. This aircraft has 3 textures instead of the standard 1, so this might be the cause. It might not be possible to fix this, since the A320 is very different than any other aircraft.

**Comment by georgegohl888** [comment]
yes it is but they were all slightly misaligned so the fix made them all work.

**Comment by waynepiekarski** [comment]
I have written some instructions in issue #4 so lets move discussion there.
