### ISSUE TITLE
Request: linux version

### ISSUE THREAD

**Issue by CyberGuerro** [waynepiekarski/XTextureExtractor#6]
Linux version could be very appreciated by linux users of x-plane :-)

**Comment by lucyydotp** [comment]
Can second this. Running X-Plane on Windows isn't a feasible option for many AMD card owners due to the lack of decent OpenGL drivers, and this would be very useful.

**Comment by waynepiekarski** [comment]
Unfortunately I don't have the time or knowledge to support a Linux build of this plugin. I would need to have a full set up for testing, and packaging up portable binaries on Linux can be a challenge. While I use Linux for much of my other development work, I use Windows for X-Plane because that is what most other 3rd party aircraft and plugins support, and the Nvidia drivers are best on Windows.

Also, XTE doesn't use official X-Plane APIs, so the trick I'm doing on Windows with Nvidia might not work on Linux with AMD, this would require some experimentation.

However, this plugin is open source, so if someone wants to work on this, I would be happy to help tell them what to do. If you know how to build a Qt app and do some basic BSD sockets code, then porting it shouldn't be too hard, its just the time needed for testing.

**Comment by waynepiekarski** [comment]
XTE release v3.1 and later now includes Linux and OSX support as well as the original Windows support. The ZIP file includes all architectures.
